apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u9bltyjcq-nodejs
  janus-idp.io/tekton: u9bltyjcq-nodejs
  backstage.io/kubernetes-id: u9bltyjcq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u9bltyjcq-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
